project:
  type: website
  output-dir: docs

website:
  title: "Joshua Fawcett Weiner"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: cv.qmd
        text: CV

format:
  html:
    theme: 
      light: sandstone
      dark: slate
    css: styles.css
    toc: true

editor: visual

