---
title: "Teaching"
---

## Instructor

[*Intrastate Conflict*](https://www.dropbox.com/scl/fi/mn9qu5bwtqeipay9qhyqr/Syllabus_Intrastate_Conflict.pdf?rlkey=h9cf3or6rhg3znld8p11gn3qj&st=88l3qjwx&dl=0) -- Summer 2022, 2023 (UBC, Undergraduate)

## Teaching Assistant

#### International Relations and Professional Development

*Professional Skills in Political Science* -- Spring 2022 (UBC, Undergraduate)\
*Security Studies* -- Spring 2021 (UBC, Undergraduate)

#### Political Methodology

*Quantitative Techniques of Political Analysis* -- Fall 2020 (UBC, Graduate)\
*Introduction to Scientific Political Analysis* -- Spring 2020 (UBC, Undergraduate)\
*Quantitative Methods in Political Science* -- Fall 2018 (UBC, Undergraduate)

## Guest Lectures

"Syria: Current Developments and Research" for the International Relations MA Group -- Spring 2025 (Radboud)\
"The End of Assad’s Rule: What Lies Ahead for Syria?" for *Radboud Reflects* -- Fall 2024 (Radboud)\
"Research Design" for the UBC *Journal of Political Studies* and the *Journal of International Affairs* -- Fall 2023 (UBC)\
"Qualitative and Quantitative Methods" for the UBC *Journal of Political Studies* -- Fall 2022 (UBC)\
"Intrastate Conflict" for *Security Studies* -- Fall 2022 (UBC, Undergraduate)\
"Development" for *Professional Skills in Political Science* -- Spring 2022 (UBC, Undergraduate)

## Supervision

Master’s Thesis Second Reader for Political Science MSc -- 2024–2025 (Radboud)

## Training

*Equity, Diversity and Inclusion in Teaching* -- September 2022 from the UBC Equity & Inclusion Office\
*Instructional Skills Workshop* -- April-May 2022 from the Centre for Teaching, Learning & Technology, UBC
